---
abstract: 'fork-safe and easy transaction handling DBI handler'
author:
  - 'Atsushi Kobayashi <nekokak _at_ gmail _dot_ com>'
build_requires:
  ExtUtils::MakeMaker: '6.36'
  Test::More: '0.94'
  Test::Requires: '0'
  Test::SharedFork: '0.16'
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v3.0.1, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DBIx-Handler
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  DBIx::Handler:
    file: lib/DBIx/Handler.pm
    version: '0.11'
requires:
  DBI: '1.605'
  DBIx::TransactionManager: '1.09'
resources:
  bugtracker: https://github.com/nekokak/p5-DBIx-Handler/issues
  homepage: https://github.com/nekokak/p5-DBIx-Handler
  repository: git://github.com/nekokak/p5-DBIx-Handler.git
version: '0.11'
x_authority: cpan:XAICRON
x_contributors:
  - 'Keiji, Yoshimi <walf443@gmail.com>'
  - 'Tasuku SUENAGA a.k.a. gunyarakun <tasuku-s-github@titech.ac>'
  - 'tokuhirom <tokuhirom@gmail.com>'
  - 'Atsushi Kobayashi <nekokak@gmail.com>'
  - 'soh335 <sugarbabe335@gmail.com>'
  - 'xaicron <xaicron@gmail.com>'
  - 'Mohammad S Anwar <mohammad.anwar@yahoo.com>'
  - 'karupanerura <karupa@cpan.org>'
